<?php

namespace CleverSwarm\BackendBundle\Repository;

/**
 * RemoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemoteRepository extends \Doctrine\ORM\EntityRepository
{
}
