cleverswarm_backend_category_index:
    path:     /
    defaults: { _controller: "CleverSwarmBackendBundle:Category:index" }
    methods:  GET

cleverswarm_backend_category_show:
    path:     /{id}/show
    defaults: { _controller: "CleverSwarmBackendBundle:Category:show" }
    methods:  GET

cleverswarm_backend_category_new:
    path:     /new
    defaults: { _controller: "CleverSwarmBackendBundle:Category:new" }
    methods:  [GET, POST]

cleverswarm_backend_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "CleverSwarmBackendBundle:Category:edit" }
    methods:  [GET, POST]

cleverswarm_backend_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "CleverSwarmBackendBundle:Category:delete" }
    methods:  DELETE
