cleverswarm_backend_post_index:
    path:     /
    defaults: { _controller: "CleversWarmBackendBundle:Post:index" }
    methods:  GET

cleverswarm_backend_post_show:
    path:     /{id}/show
    defaults: { _controller: "CleversWarmBackendBundle:Post:show" }
    methods:  GET

cleverswarm_backend_post_new:
    path:     /new
    defaults: { _controller: "CleversWarmBackendBundle:Post:new" }
    methods:  [GET, POST]

cleverswarm_backend_post_edit:
    path:     /{id}/edit
    defaults: { _controller: "CleversWarmBackendBundle:Post:edit" }
    methods:  [GET, POST]

cleverswarm_backend_post_delete:
    path:     /{id}/delete
    defaults: { _controller: "CleversWarmBackendBundle:Post:delete" }
    methods:  DELETE
