cleverswarm_frontend_post_index:
    path:     /
    defaults: { _controller: CleversWarmFrontendBundle:Post:index }

cleverswarm_frontend_post_show:
    path:     /{id}/show
    defaults: { _controller: CleversWarmFrontendBundle:Post:show }