cleverswarm_frontend_remote_index:
    path:     /
    defaults: { _controller: CleverSwarmFrontendBundle:Remote:index }
    methods:  GET

cleverswarm_frontend_remote_show:
    path:     /{id}/show
    defaults: { _controller: CleverSwarmFrontendBundle:Remote:show }
    methods:  GET