cleverswarm_frontend_index:
    path:     /
    defaults: { _controller: CleversWarmFrontendBundle:Main:index }

cleverswarm_frontend_remote:
    resource: "@CleversWarmFrontendBundle/Resources/config/routing/remote.yml"
    prefix:   /remote
