cleverswarm_backend_remote:
    resource: "@CleverSwarmBackendBundle/Resources/config/routing/remote.yml"
    prefix:   /remote

cleverswarm_backend_index:
    path:     /
    defaults: { _controller: CleverSwarmBackendBundle:Main:index }

cleverswarm_backend_post:
    resource: "@CleverSwarmBackendBundle/Resources/config/routing/post.yml"
    prefix:   /post